steps:    
  ### Build
  - id: 'docker-build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/assesment:$REVISION_ID', '.']

  ### Publish
  - id: 'docker-push'
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/assesment:$REVISION_ID"]

  ### Deploy
  - id: 'helm-deploy'
    name: 'gcr.io/$PROJECT_ID/helm'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    args: [
      'upgrade', '--install','--force', 'assesment-$_test_ENV',
      '--namespace', '$_assesment_ENV', '-f', '.helm/values.$_assesment_ENV.yaml',
      '--set', 'assesment.image=gcr.io/$PROJECT_ID/assesment:$REVISION_ID',
      '.helm'
    ]


timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/assesment'
